[package]
edition = "2018"
name = "bench_vtables"
version = "0.1.0"

[lib]

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }

[dependencies]
bitintr = "0.3.0"
succinct = "0.5.2"

[features]
slow_pdep = []

[[bench]]
harness = false
name = "fibonacci"
